/**
 * Sample Events Data — Initial 10 events for the system
 * These are loaded once on first app launch (if localStorage is empty).
 */

const now = new Date();
const addDays = (d, days) => {
  const r = new Date(d);
  r.setDate(r.getDate() + days);
  return r.toISOString().split('T')[0];
};

export const SAMPLE_EVENTS = [
  {
    id: 'evt-001',
    name: 'AI & Machine Learning Workshop',
    category: 'Technology',
    date: addDays(now, 15),
    time: '10:00 AM',
    venue: 'Tech Hub Auditorium, Bangalore',
    description: 'An intensive hands-on workshop covering supervised learning, neural networks, and deploying ML models. Industry experts will guide participants through real-world use cases using Python, TensorFlow, and scikit-learn. Perfect for students and early-career professionals.',
    price: 499,
    totalSeats: 100,
    availableSeats: 100,
    bookingsCount: 0,
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80',
    isFeatured: true,
    tags: ['AI', 'ML', 'Python', 'TensorFlow'],
  },
  {
    id: 'evt-002',
    name: 'College Cultural Fest 2026',
    category: 'Cultural',
    date: addDays(now, 8),
    time: '04:00 PM',
    venue: 'Main Ground, Sri Venkateswara College',
    description: 'A grand annual cultural extravaganza featuring music, dance, drama, art exhibitions, and fashion shows. Celebrate creativity and talent across disciplines. Open to all students and faculty.',
    price: 0,
    totalSeats: 100,
    availableSeats: 100,
    bookingsCount: 0,
    image: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&q=80',
    isFeatured: true,
    tags: ['Culture', 'Music', 'Dance', 'Free'],
  },
  {
    id: 'evt-003',
    name: 'Tech Innovation Summit',
    category: 'Technology',
    date: addDays(now, 22),
    time: '09:00 AM',
    venue: 'Hyderabad International Convention Centre',
    description: 'Join leading innovators, startup founders, and investors for a day of inspiring talks on Web3, quantum computing, AR/VR, and green tech. Network with 500+ professionals and explore the future of technology.',
    price: 1499,
    totalSeats: 100,
    availableSeats: 100,
    bookingsCount: 0,
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
    isFeatured: true,
    tags: ['Innovation', 'Startups', 'Networking'],
  },
  {
    id: 'evt-004',
    name: 'Inter-College Cricket Tournament',
    category: 'Sports',
    date: addDays(now, 5),
    time: '08:00 AM',
    venue: 'Chinnaswamy Stadium Outfield, Bangalore',
    description: 'The most anticipated cricket tournament of the year! 16 college teams compete over 2 days in T20 format. Watch your favorite team battle for the champion trophy. Food stalls and live commentary throughout.',
    price: 150,
    totalSeats: 100,
    availableSeats: 100,
    bookingsCount: 0,
    image: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&q=80',
    isFeatured: false,
    tags: ['Cricket', 'Sports', 'T20'],
  },
  {
    id: 'evt-005',
    name: '24-Hour Coding Hackathon',
    category: 'Technology',
    date: addDays(now, 30),
    time: '06:00 PM',
    venue: 'BITS Pilani Innovation Hub',
    description: 'Build something amazing in 24 hours! Themes include HealthTech, FinTech, and CleanTech. Prizes worth ₹5 Lakhs. Mentors from top companies. Food, energy drinks, and sleeping pods provided.',
    price: 200,
    totalSeats: 100,
    availableSeats: 100,
    bookingsCount: 0,
    image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&q=80',
    isFeatured: true,
    tags: ['Hackathon', 'Coding', 'Prizes'],
  },
  {
    id: 'evt-006',
    name: 'Sunburn Music Festival',
    category: 'Music',
    date: addDays(now, 45),
    time: '03:00 PM',
    venue: 'Vagator Beach, Goa',
    description: "Asia's biggest electronic music festival returns! Featuring 30+ international and Indian DJs across 3 stages. 3-day camping, art installations, food courts, and an unforgettable beach experience.",
    price: 2999,
    totalSeats: 100,
    availableSeats: 100,
    bookingsCount: 0,
    image: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80',
    isFeatured: true,
    tags: ['EDM', 'Festival', 'Beach', 'DJs'],
  },
  {
    id: 'evt-007',
    name: 'Full-Stack Web Development Bootcamp',
    category: 'Workshops',
    date: addDays(now, 12),
    time: '09:30 AM',
    venue: 'Coding Dojo, Pune',
    description: 'A 2-day immersive bootcamp on React, Node.js, MongoDB, and deployment with Docker and AWS. Build and deploy a full-stack project from scratch. Certificate of completion provided.',
    price: 799,
    totalSeats: 60,
    availableSeats: 60,
    bookingsCount: 0,
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80',
    isFeatured: false,
    tags: ['React', 'Node.js', 'Web Dev', 'Certificate'],
  },
  {
    id: 'evt-008',
    name: 'Entrepreneurship & Startup Meetup',
    category: 'College Events',
    date: addDays(now, 10),
    time: '02:00 PM',
    venue: 'IIM Ahmedabad, Seminar Hall',
    description: 'Connect with founders, VCs, and mentors. Hear success stories, pitch your idea in front of investors, and attend workshops on product-market fit, fundraising, and scaling your startup.',
    price: 299,
    totalSeats: 100,
    availableSeats: 100,
    bookingsCount: 0,
    image: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800&q=80',
    isFeatured: false,
    tags: ['Startup', 'Entrepreneurship', 'Networking'],
  },
  {
    id: 'evt-009',
    name: 'Photography & Visual Storytelling Workshop',
    category: 'Workshops',
    date: addDays(now, 18),
    time: '11:00 AM',
    venue: 'National Gallery of Modern Art, Mumbai',
    description: 'Learn composition, lighting, portrait and street photography, and post-processing with Lightroom. Professional photographers share their workflow. Hands-on shooting sessions in the gallery and surrounding areas.',
    price: 599,
    totalSeats: 40,
    availableSeats: 40,
    bookingsCount: 0,
    image: 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800&q=80',
    isFeatured: false,
    tags: ['Photography', 'Art', 'Creative'],
  },
  {
    id: 'evt-010',
    name: 'Cybersecurity & Ethical Hacking Seminar',
    category: 'Technology',
    date: addDays(now, 25),
    time: '10:00 AM',
    venue: 'IIT Delhi, Computer Science Block',
    description: 'Explore penetration testing, vulnerability assessment, OWASP Top 10, and defensive security strategies. CTF (Capture the Flag) competition with prizes. Certifications from EC-Council recognized.',
    price: 699,
    totalSeats: 100,
    availableSeats: 100,
    bookingsCount: 0,
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80',
    isFeatured: true,
    tags: ['Cybersecurity', 'Hacking', 'CTF', 'Security'],
  },
];

export const CATEGORIES = [
  { id: 'all', name: 'All Events', icon: '🎯' },
  { id: 'Technology', name: 'Technology', icon: '💻' },
  { id: 'Music', name: 'Music', icon: '🎵' },
  { id: 'Sports', name: 'Sports', icon: '🏏' },
  { id: 'Workshops', name: 'Workshops', icon: '🔧' },
  { id: 'Cultural', name: 'Cultural', icon: '🎭' },
  { id: 'College Events', name: 'College Events', icon: '🎓' },
];

export const ADMIN_CREDENTIALS = {
  email: 'admin@eventbook.com',
  password: 'Admin@123',
  name: 'System Administrator',
  role: 'admin',
};
